# Generated by Django 4.2.3 on 2023-07-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mockDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Мурманск', max_length=12, verbose_name='Название')),
                ('t', models.CharField(default='0', max_length=2, verbose_name='Температура')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
