# Generated by Django 4.2.3 on 2023-07-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(verbose_name='Дни недели'),
        ),
    ]
