# Generated by Django 4.2.3 on 2023-07-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_weather_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.CharField(default='Мурманск', max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(verbose_name='Выбрать день и время'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='t',
            field=models.IntegerField(verbose_name='Температура'),
        ),
    ]
